### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by carolfly86** [citusdata/pg_shard#125]
I get the error below when building `pg_shard` on RHEL6 using GCC 4.4:

```
gcc -O2 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fpic -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Iinclude -I/opt/citusdb/4.0/include -Itest/include -I. -I./ -I/opt/citusdb/4.0/include/postgresql/server -I/opt/citusdb/4.0/include/postgresql/internal -D_GNU_SOURCE   -c -o src/ruleutils_94.o src/ruleutils_94.c
cc1: warnings being treated as errors
src/ruleutils_94.c:74: error: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
src/ruleutils_94.c:6518: error: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
make: *** [src/ruleutils_94.o] Error 1

echo $PATH
/opt/citusdb/4.0/bin/:/usr/pgsql-9.4/bin/:/sbin:/bin:/usr/sbin:/usr/bin
```

Is it something wrong with my `gcc`? Any suggestion on how to fix it?

**Comment by jasonmp85** [comment]
Hey @carolfly86: I noticed you also [asked this question](https://groups.google.com/d/msg/pg_shard-users/1KxZH7DvFhk/78B1ujLcyyUJ) in the [pg_shard users Google Group](https://groups.google.com/forum/#!forum/pg_shard-users). I've answered your question there.

I'm marking this ticket as documentation to remind me to update our `README` with a minimum GCC version.

**Comment by jasonmp85** [comment]
I've added a sentence about required GCC version in the latest `README`.
