### ISSUE TITLE
1.2.1 build error against PostgreSQL 9.5

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/pg_shard#142]
Hi,

I'm getting this while trying to build 1.2.1 against PostgreSQL 9.5 Alpha 2 on Fedora 22 box:

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Iinclude -I/usr/pgsql-9.5/include -Itest/include -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o test/src/distribution_metadata.o test/src/distribution_metadata.c
src/generate_ddl_commands.c: In function 'TableDDLCommandList':
src/generate_ddl_commands.c:131:19: error: implicit declaration of function 'pg_get_constraintdef_string' [-Werror=implicit-function-declaration]
    statementDef = pg_get_constraintdef_string(constraintId);
                   ^
src/generate_ddl_commands.c:131:17: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
    statementDef = pg_get_constraintdef_string(constraintId);
                 ^
src/generate_ddl_commands.c:135:19: error: implicit declaration of function 'pg_get_indexdef_string' [-Werror=implicit-function-declaration]
    statementDef = pg_get_indexdef_string(indexId);
                   ^
src/generate_ddl_commands.c:135:17: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
    statementDef = pg_get_indexdef_string(indexId);
                 ^
src/generate_ddl_commands.c: In function 'pg_shard_get_tableschemadef_string':
src/generate_ddl_commands.c:263:22: error: implicit declaration of function 'deparse_context_for' [-Werror=implicit-function-declaration]
     defaultContext = deparse_context_for(relationName, tableRelationId);
                      ^
src/generate_ddl_commands.c:263:20: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     defaultContext = deparse_context_for(relationName, tableRelationId);
                    ^
src/generate_ddl_commands.c:266:21: error: implicit declaration of function 'deparse_expression' [-Werror=implicit-function-declaration]
     defaultString = deparse_expression(defaultNode, defaultContext,
                     ^
src/generate_ddl_commands.c:266:19: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     defaultString = deparse_expression(defaultNode, defaultContext,
                   ^
src/generate_ddl_commands.c:310:16: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
   checkContext = deparse_context_for(relationName, tableRelationId);
                ^
src/generate_ddl_commands.c:313:15: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
   checkString = deparse_expression(checkNode, checkContext, false, false);
               ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'src/generate_ddl_commands.o' failed
make[1]: *** [src/generate_ddl_commands.o] Error 1
make[1]: *** Waiting for unfinished jobs....
src/extend_ddl_commands.c: In function 'DeparseCreateStmt':
src/extend_ddl_commands.c:608:28: error: implicit declaration of function 'deparse_context_for' [-Werror=implicit-function-declaration]
     List *defaultContext = deparse_context_for(masterRelationName,
                            ^
src/extend_ddl_commands.c:608:28: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
src/extend_ddl_commands.c:610:32: error: implicit declaration of function 'deparse_expression' [-Werror=implicit-function-declaration]
     char *defaultValueString = deparse_expression(plannedExpression,
                                ^
src/extend_ddl_commands.c:610:32: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
src/extend_ddl_commands.c:655:16: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
   checkContext = deparse_context_for(masterRelationName, masterRelationId);
                ^
src/extend_ddl_commands.c:656:15: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
   checkString = deparse_expression(plannedExpression, checkContext, false, false);
               ^
src/extend_ddl_commands.c: In function 'DeparseIndexStmt':
src/extend_ddl_commands.c:787:24: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
    List *exprContext = deparse_context_for(masterRelationName, masterRelationId);
                        ^
src/extend_ddl_commands.c:788:23: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
    char *exprString = deparse_expression(expression, exprContext, false, false);
                       ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'src/extend_ddl_commands.o' failed
make[1]: *** [src/extend_ddl_commands.o] Error 1
make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/9.5/pg_shard/F-22/pg_shard-1.2.1'
error: Bad exit status from /var/tmp/rpm-tmp.89c3bM (%build)

Regards, Devrim

**Comment by onderkalaci** [comment]
Hi @devrimgunduz,

We already have a [PR](https://github.com/citusdata/pg_shard/pull/137) for 9.5 compatibility, which we plan to merge soon.

Thanks!

**Comment by jasonmp85** [comment]
Closing. PostgreSQL 9.5 alpha 1 wasn't even released until _after_ `pg_shard v1.2.1`, so there's no way this build could pass.

We _are_ tracking 9.5 compatibility in our `develop` branch, and build against it with every Travis CI build ever since #137 was merged.
