### ISSUE TITLE
Handling bigserial / auto-increment [Moved to mailing list]

### ISSUE THREAD

**Issue by ColonelBundy** [citusdata/pg_shard#157]
I'm fairly new to pg_shard and citusdb and to my understanding there's no way to actually support a type of auto-increment feature? if not how to properly handle this?

**Comment by onderkalaci** [comment]
Hi @makkesk8, 

Thanks for reaching out. We generally use pg_shard mailing list for this kind of discussions and there is already a similar question there. You can use [this link](https://groups.google.com/forum/#!searchin/pg_shard-users/auto-increment/pg_shard-users/97dvCPUqWGU/APMvXSELEwAJ) to reach the question.

If it doesn't help for your case, could you start a new thread in the google groups?

I am closing this issue there.

Thanks
