### ISSUE TITLE
Queries with CTEs produce misleading error

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/pg_shard#46]
This is a pretty simple bug: queries with a CTE generate an error message about JOINs (_Joins are currently unsupported_) rather than one about CTEs. Check out this [test output][] to see what I mean.

I'd expect the error message to say something about CTEs being unsupported.

[test output]: https://github.com/citusdata/pg_shard/blob/fcf844ce828f85f7c3ad769083b3050cc459393f/expected/modifications.out.tmpl#L90-L94

**Comment by onderkalaci** [comment]
@jasonmp85 This will be solved with  [pull request 51](https://github.com/citusdata/pg_shard/pull/51). When we merge the pull request, we can close this issue.
