### ISSUE TITLE
Support enumeration types for partition columns

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/pg_shard#80]
This is similar to #79 except maybe more surprising that it doesn't _Just Work™_:

```sql
CREATE TYPE bug_status AS ENUM ('new', 'open', 'closed');
# CREATE TYPE
# Time: 6.044 ms

CREATE TABLE bugs (
    id integer,
    status bug_status
);
# CREATE TABLE
# Time: 3.599 ms

SELECT master_create_distributed_table('bugs', 'status');
# ERROR:  42883: could not identify a hash function for type bug_status
# DETAIL:  Partition column types must have a hash function defined to use hash partitioning.
# LOCATION:  master_create_distributed_table, create_shards.c:109
# Time: 3.202 ms
```

Kinda weird that enum types don't have a built-in hash function defined, given they're basically glorified integers.

**Comment by jasonmp85** [comment]
Strangely, while `hash_array` fails to hash an array of a custom composite type (_could not identify a hash function for type…_), it _can_ hash an array of an enumerated type. So perhaps we should look at it to see whether we're looking up hash functions in the best way possible.

**Comment by onderkalaci** [comment]
@jasonmp85 So, this might be related to the patch applied to citus very recently (Composite Type bug fix (New version)).

So, I'll check this too, missed that while checking for #79 .

**Comment by jasonmp85** [comment]
Oh, I think I misled. I said that `hash_array` could find a function for composite types (#79), but I think I was confusing that with this (enumeration types). So we're on our own for composite types, but as I said above, it's kinda weird that we don't find the right function for an enumeration type.
