### ISSUE TITLE
Collocated JOINs support

### ISSUE THREAD

**Issue by jsuchal** [citusdata/pg_shard#90]
Hi,

opening this based on discussion here https://groups.google.com/d/msg/pg_shard-users/tFXGdSjCcMs/q4wKNW_I9yYJ.

The idea is to allow JOINs for data that are guaranteed to be collocated on shard. 

> I can think of ways we could come up with a “partition scheme” and have multiple tables use the same scheme so that values of a given column are guaranteed to be collocated. Then if a JOIN between two (or more) tables with that scheme comes in, we can safely push down that JOIN. Does this sound like what you’re looking for?

This is exactly it.

**Comment by jasonmp85** [comment]
Thanks for the feature request! We discussed this feature among the team and decided we won't be working on it in the near future, at least not within `pg_shard`. As I mentioned in the Google Groups thread, CitusDB does benefit from collocated `JOIN` configurations.
