### ISSUE TITLE
copy_to_distributed_table is not working

### ISSUE THREAD

**Issue by arunnairmr** [citusdata/pg_shard#97]
copy_to_distributed_table command is not working for me.

postgres=# copy_to_distributed_table -CH -d '|' -n NULL '/home/ubuntu/customer_reviews_1998.csv' customer_reviews;
ERROR:  syntax error at or near "copy_to_distributed_table"
LINE 1: copy_to_distributed_table -CH -d '|' -n NULL '/home/ubuntu/c...

Is there anything wrong in this command.

**Comment by onderkalaci** [comment]
Hey @arunnairmr,

`copy_to_distributed_table` is not a UDF. It is a bash script located under the `bin` directory of the source code. 

The command looks correct, but, it needs to be executed it from the shell, such as:
``` ./copy_to_distributed_table -CH -d '|' -n NULL '/home/ubuntu/customer_reviews_1998.csv' customer_reviews```

We primarily try to use github for new feature requests and bug reports. We also have a [mailing list](https://groups.google.com/forum/#!forum/pg_shard-users), where these kind of discussions seems more appropriate. 

Thanks for reaching out us!
